"""Added image column to model

Revision ID: 1dc42cdbb6bc
Revises: 2b7a159e5f55
Create Date: 2023-07-19 23:25:32.444753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc42cdbb6bc'
down_revision = '2b7a159e5f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'image')
    # ### end Alembic commands ###
